line-length = 99
extend-exclude = ["lib"]

[lint]
select = [
    "E",
    "W",
    "F",
    "C4",
    "N",
    "D",
    "I",
    "UP",
    "B",
    "RUF",
]
ignore = [
    "D105",
    "D107",
    "D203",
    "D204",
    "D213",
    "D215",
    "D400",
    "D404",
    "D406",
    "D407",
    "D408",
    "D409",
    "D413",
]

[lint.per-file-ignores]
"**/tests/**" = ["S101", "D", "S105", "S106", "S108", "PLR2004", "ARG", "SLF001", "N802", "N803", "N806"]
